/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#353534',
        'on-primary-fixed': '#3e001f',
        'primary-fixed-dim': '#ffb0cb',
        'surface': '#131313',
        'on-secondary': '#00363a',
        'on-primary-container': '#58002f',
        'tertiary-fixed-dim': '#dfb7ff',
        'surface-container-high': '#2a2a2a',
        'on-surface-variant': '#e2bdc7',
        'tertiary-container': '#ba6bff',
        'primary-container': '#ff479c',
        'tertiary': '#dfb7ff',
        'surface-variant': '#353534',
        'primary': '#ffb0cb',
        'on-secondary-container': '#00686f',
        'error-container': '#93000a',
        'secondary-container': '#00eefc',
        'on-error': '#690005',
        'surface-bright': '#393939',
        'secondary-fixed-dim': '#00dbe9',
        'secondary-fixed': '#7df4ff',
        'error': '#ffb4ab',
        'outline': '#a98892',
        'tertiary-fixed': '#f1daff',
        'on-primary': '#640036',
        'surface-dim': '#131313',
        'surface-tint': '#ffb0cb',
        'primary-fixed': '#ffd9e3',
        'on-background': '#e5e2e1',
        'on-primary-fixed-variant': '#8d004f',
        'on-secondary-fixed-variant': '#004f54',
        'secondary': '#d3fbff',
        'inverse-primary': '#b80068',
        'surface-container': '#201f1f',
        'surface-container-lowest': '#0e0e0e',
        'inverse-on-surface': '#313030',
        'on-tertiary': '#4b007e',
        'on-error-container': '#ffdad6',
        'background': '#131313',
        'outline-variant': '#5a3f48',
        'inverse-surface': '#e5e2e1',
        'on-tertiary-container': '#41006f',
        'surface-container-low': '#1c1b1b',
        'on-surface': '#e5e2e1',
        'on-tertiary-fixed': '#2d004f',
        'on-secondary-fixed': '#002022',
        'on-tertiary-fixed-variant': '#6b00b0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '24px',
        gutter: '20px',
        xl: '64px',
        sm: '12px',
        base: '8px',
        xs: '4px',
        lg: '40px',
      },
      fontFamily: {
        'display-xl': ['Space Grotesk'],
        'headline-md': ['Space Grotesk'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-sm': ['Space Grotesk'],
        'headline-lg': ['Space Grotesk'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
