// Mora — sample memories. Calm editorial copy throughout.
window.MORA_DATA = {
  memories: [
    {
      id: "m1",
      type: "song",
      source: "Spotify",
      title: "Slow Show",
      author: "The National",
      body: "A song for long evenings, kept playing through the spring.",
      time: "Last spring",
      tags: ["evening", "drift", "re-listen"],
      kept: true,
      thumb: "linear-gradient(135deg, #4A3F30 0%, #2E4051 100%)",
    },
    {
      id: "m2",
      type: "note",
      source: "Mora · Journal",
      title: "On unfinished things",
      body: "The interface should feel like a memory — slightly imperfect, profoundly resonant. Not as a feature, but as a posture toward what we keep.",
      time: "Tuesday in October",
      tags: ["design", "philosophy"],
      kept: true,
    },
    {
      id: "m3",
      type: "image",
      source: "Pinterest",
      title: "Sienna terraces, off-season",
      body: "From a board called \"things in warm light.\"",
      time: "Sometime in 2023",
      tags: ["aesthetic", "warmth"],
      thumb: "linear-gradient(135deg, #B6532E 0%, #B89B5E 100%)",
      kept: false,
    },
    {
      id: "m4",
      type: "reading",
      source: "Nytimes",
      title: "The shape of a week",
      body: "An essay on how Tuesdays and Thursdays fold differently. You underlined two paragraphs.",
      time: "A Sunday in March",
      tags: ["reading", "time"],
      kept: false,
    },
    {
      id: "m5",
      type: "video",
      source: "YouTube",
      title: "How a bookbinder works",
      body: "Twenty quiet minutes of paper folding and beeswax.",
      time: "Last winter",
      tags: ["craft", "calm"],
      thumb: "linear-gradient(135deg, #5C6A4D 0%, #1E1A14 100%)",
      kept: false,
    },
    {
      id: "m6",
      type: "note",
      source: "Mora · Journal",
      title: "A small thing",
      body: "Caught myself smiling at the way the kitchen smelled this morning. Bread and rosemary. Want to remember.",
      time: "This morning",
      tags: ["small things", "mornings"],
      kept: true,
    },
    {
      id: "m7",
      type: "song",
      source: "Spotify",
      title: "Cruel Summer",
      author: "Bananarama, 1983",
      body: "From a playlist your sister sent. Played twice in July.",
      time: "Two summers ago",
      tags: ["summer", "from-cara"],
      thumb: "linear-gradient(135deg, #B89B5E 0%, #B6532E 100%)",
      kept: false,
    },
    {
      id: "m8",
      type: "reading",
      source: "Are.na",
      title: "Notebooks as a practice",
      body: "A channel of 47 entries on why people keep paper notebooks. Half are out of print.",
      time: "Yesterday",
      tags: ["notebooks", "practice"],
      kept: true,
    },
    {
      id: "m9",
      type: "image",
      source: "Manual",
      title: "The reading nook, late afternoon",
      body: "A photo from the chair by the window.",
      time: "A Sunday",
      tags: ["home"],
      thumb: "linear-gradient(135deg, #DCD1B8 0%, #B89B5E 100%)",
      kept: false,
    },
    {
      id: "m10",
      type: "note",
      source: "Mora · Journal",
      title: "Something Aileen said",
      body: "\"You're not behind. You're just here.\" Need to put this somewhere I'll find it again.",
      time: "Thursday",
      tags: ["from-aileen", "kept"],
      kept: true,
    },
  ],

  constellations: [
    { tag: "evening",     count: 12, blurb: "songs, films, and small thoughts kept for after dark" },
    { tag: "design",       count: 28, blurb: "the long-running thread — typography, paper, slow tools" },
    { tag: "from-aileen",  count: 7, blurb: "things shared by a friend, a small archive of her" },
    { tag: "small things", count: 19, blurb: "the smell of bread, the way light moves at four o'clock" },
    { tag: "re-read",      count: 9, blurb: "marked for a second visit, when you're ready" },
  ],

  resurface: {
    intro: "Three memories from the past, brought up by something you saved this week.",
    items: ["m2", "m4", "m7"],
  },
};
